services:
  toybank:
    # Use the image you built locally with the updated app.py file
    image: ghcr.io/jhjang101/toybank:latest

    # Give container name
    container_name: toybank

    # Instruct Docker to restart the container if it stops unexpectedly
    restart: always 
    
    # Map the container port (8000) to the host machine port (8000)
    ports:
    - "8000:8000"

    # read .env file and set variables as environment variables into the container
    env_file:
    - .env
    
    # Map the data folder in the container to one on the host
    volumes:
    - ./data:/toybank/app/data